[package]
name = "jfs"
version = "0.2.1"
authors = ["Markus Kohlhase <mail@markus-kohlhase.de>"]
license = "MIT"
homepage = "https://github.com/flosse/rust-json-file-store"
repository = "https://github.com/flosse/rust-json-file-store"
description = "A JSON file store"
keywords = ["json", "file", "store", "db", "database"]

[dependencies]
fs2 = "0.2"
uuid = { version = "0.2", features = ["v4"] }
rustc-serialize = { version = "0.3", optional = true }
serde = { version = "0.7", optional = true }
serde_json = { version = "0.7", optional = true }
serde_macros = { version = "0.7", optional = true }

[features]
default = ["rustc-serialize"]
